### ISSUE TITLE
Standard Event Implementation

### ISSUE THREAD

**Issue by natterstefan** [dominikmatt/trackingJS#13]
Please include standard events like (note: $var represents a variable)

Download: Download // Download - $filetype // Download: $filname ($filetype)
Contact - Mail: Contact // Contact - Mail // Contact: $mailaddress
Contact - Tel: Contact // Contact - Tel // Contact: $telelephonenumber
External Link: Link // Link - External Link  // External Link: $target
Social Media ($type = ie. share, follow ...): Social Media // Social Media - $type $network // Social Media: $type $network

If you have any questions, just ask.

Stefan

**Comment by dominikmatt** [comment]
External Link - done
Social Media - done
Contact - done
