### ISSUE TITLE
custom dimension and metric implementation

### ISSUE THREAD

**Issue by natterstefan** [dominikmatt/trackingJS#35]
Universal Analytics supports creating custom metrics and dimensions. The user can set it on hit, session and user level in universal analytics. The trackingJS then should add it accordingly when a user fires a pageview or an event.

Docs: https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets
Example: ga("set", "dimension1", "first variant")

**Comment by dominikmatt** [comment]
done
